project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Exploratory Data Analysis of the Golub Gene Expression Dataset"
  author:
    - Naman Bareja (nb3236)
    - Pranav Bidve (pb2972)
  repo-url: https://github.com/pranavbidve/golub-gene
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: vapor
    css: custom.css
    code-fold: true


